package DCMSApp;


/**
* DCMSApp/DCMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/Eclipse/workspace/COMP6231_Project/src/DCMS.idl
* Friday, July 28, 2017 10:51:04 o'clock AM EDT
*/

public interface DCMS extends DCMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DCMS
